<a href="https://colab.research.google.com/github/jeonyeohun/2020_2_DeepLearning_Application/blob/master/HW_3_linear_classifiers.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [292]:
import numpy as np
import sklearn as sk
from sklearn.model_selection import train_test_split

TO DO: import load_wine from sklearn.datasets
 Then, create an instance __dataset__ by calling load_wine()

In [293]:
from sklearn.datasets import load_wine 
dataset = load_wine()

TO DO: Display dataset.keys() and the elements of dataset.

In [294]:
dataset.keys()

dict_keys(['data', 'target', 'target_names', 'DESCR', 'feature_names'])

TO DO: Split dataset into train and test sets, and print the shape of X_train, y_train, X_test and y_test

In [295]:
X_train, X_test, y_train, y_test = train_test_split(dataset['data'], dataset['target'])

print('X_train.shape = ', X_train.shape)
print('y_train.shape = ', y_train.shape)
print('X_test.shape = ', X_test.shape)
print('y_test.shape = ', y_test.shape)


X_train.shape =  (133, 13)
y_train.shape =  (133,)
X_test.shape =  (45, 13)
y_test.shape =  (45,)


TO DO: Build a classifier for the wine dataset using LogisicRegression, and print the accuracy on the training and test data.


In [296]:
from sklearn.linear_model import LogisticRegression

logi = LogisticRegression().fit(X_train, y_train)
logi_result = logi.predict(X_test)

print('train score = ', logi.score(X_train, y_train))
print('test score = ', logi.score(X_test, y_test))

train score =  0.9624060150375939
test score =  1.0


/usr/local/lib/python3.6/dist-packages/sklearn/linear_model/_logistic.py:940: ConvergenceWarning: lbfgs failed to converge (status=1):
STOP: TOTAL NO. of ITERATIONS REACHED LIMIT.

Increase the number of iterations (max_iter) or scale the data as shown in:
    https://scikit-learn.org/stable/modules/preprocessing.html
Please also refer to the documentation for alternative solver options:
    https://scikit-learn.org/stable/modules/linear_model.html#logistic-regression
  extra_warning_msg=_LOGISTIC_SOLVER_CONVERGENCE_MSG)


TO DO: Save the weight matrix and bias vector of the LogisticRegression instance as W_lr and b_lr. Then, print them.

In [297]:
W_lr = logi.coef_
print('W_lr = ', W_lr)

b_lr = logi.intercept_
print('b_lr = ', b_lr)

W_lr =  [[-1.50251731e-01  2.60622568e-01  1.81493258e-01 -1.75011976e-01
  -3.40662812e-02  2.16231070e-01  5.51877142e-01 -1.86392471e-02
   1.15326283e-01 -4.42996090e-02 -6.40727101e-03  3.49554127e-01
   8.03170315e-03]
 [ 5.39366497e-01 -6.90705794e-01 -1.72718438e-01  1.86084160e-01
  -5.91676101e-03  2.70924116e-01  4.06994684e-01  2.21067195e-02
   3.18898997e-01 -1.08904399e+00  2.18666108e-01  3.42900498e-01
  -7.91627826e-03]
 [-3.89114765e-01  4.30083226e-01 -8.77481986e-03 -1.10721838e-02
   3.99830422e-02 -4.87155186e-01 -9.58871826e-01 -3.46747239e-03
  -4.34225279e-01  1.13334360e+00 -2.12258837e-01 -6.92454625e-01
  -1.15424888e-04]]
b_lr =  [-0.0466068   0.09915712 -0.05255031]


TO DO: Build a classifier for the wine dataset using LinearSVC, and print the accuracy on the training and test data.

In [298]:
from sklearn.svm import LinearSVC

lsvc = LinearSVC().fit(X_train, y_train)
svc_result = lsvc.predict(X_test)

print('train score = ', lsvc.score(X_train, y_train))
print('test score = ', lsvc.score(X_test, y_test))

train score =  0.8571428571428571
test score =  0.9555555555555556


/usr/local/lib/python3.6/dist-packages/sklearn/svm/_base.py:947: ConvergenceWarning: Liblinear failed to converge, increase the number of iterations.
  "the number of iterations.", ConvergenceWarning)


TO DO: Save the weight matrix and bias vector of the LinearSVC instance as W_svc and b_svc. Then, print them.

In [299]:
W_svc = lsvc.coef_
print('W_svc = ', W_svc)

b_svc = lsvc.intercept_
print('b_svc = ', b_svc)

W_svc =  [[-3.76160444e-02 -5.21198828e-03 -2.41647503e-04 -9.67543793e-02
  -7.75200627e-03  7.85725086e-03  2.86339022e-02 -3.66743419e-03
   6.63495194e-03 -2.96150039e-02 -9.83336044e-04  1.33064794e-02
   2.69760056e-03]
 [ 4.21345334e-02 -8.22203744e-02 -4.34570210e-03  3.70362956e-02
   6.80986180e-03  4.75363609e-02  7.99634882e-02  4.46929460e-04
   4.89818191e-02 -1.85924226e-01  2.64239612e-02  7.10545845e-02
  -2.88466275e-03]
 [-2.97856143e-02  8.17459461e-02  1.97560247e-04  3.51764162e-03
  -4.93350963e-03 -6.73238242e-02 -1.36374234e-01  3.06531429e-03
  -5.84441024e-02  2.11488485e-01 -2.66050975e-02 -9.98518416e-02
   1.52794952e-04]]
b_svc =  [-0.00453796  0.00837967 -0.00557702]


TO DO: Define a class __SimpleLinearClassifier__ composed of the following functions:

* __\_\_init\_\___(self, weight, bias) - takes a weight matrix and a bias vector as input and stores them in instance variables

* __predict(self, X)__ - takes an array of rank 2 as input, and returns the classification results as an array of rank 1

* __probability(self, X)__ - takes an array of rank 2 as input and returns the probabilities that each sample belongs to each class as an array of rank 2. (You need to implement the softmax function to convert logits into probabilities.)

* __score(self, X, y)__ - takes an input data (rank 2) and a target vector (rank 1) as input, and returns the accuracy as a scalar value.


The __SimpleLinearClassifier__ should work as the following examples.

In [300]:
# Define SimpleLienarClassfier here.
class SimpleLinearClassifier:
  def __init__(self, weight, bias):
    self.weight = weight
    self.bias = bias

  def sigmoid(self, x):
    return 1 / (1 + np.exp(-(x)))

  def predict(self, X):
    pred_result = []
    for xi in X:
      rank = 0
      val = 0
      for j in range(len(self.weight)):
        class_score = self.sigmoid(np.matmul(self.weight[j], np.transpose(xi)) + self.bias[j])
        if (val < class_score):
          val = class_score
          rank = j
      pred_result.append(rank)
        
    return np.array(pred_result)

  def softmax (self, a):
    c = np.max(a)
    exp_a = np.exp(a-c)
    sum_exp_a = np.sum(exp_a)
    y = exp_a / sum_exp_a

    return y

  def probability (self, X):
    prob_result = []
    for xi in X:
      sig = []
      for w, b in zip(self.weight, self.bias):
        sig.append(np.matmul(w, np.transpose(xi)) + b)
      prob_result.append(self.softmax(np.array(sig)))
      
    return np.array(prob_result)
  

  def score (self, X, y):
    pred = (self.predict(X) == y)
    return np.mean(pred)



TO DO: Create a SimpleLinearClassfier instance simple_lr using W_lr and b_lr. Then, print the accuracy on the training and test data.<br>
(The accuracies should be the same as those of the LogisticRegression instance.)

In [301]:
simple_lr = SimpleLinearClassifier(W_lr, b_lr)
print('train score = ', simple_lr.score(X_train, y_train))
print('test score = ', simple_lr.score(X_test, y_test))


train score =  0.9624060150375939
test score =  1.0


TO DO: Display the results of simple_lr.predict(X_test) along with y_test.

In [302]:
print('y_hat = ' , simple_lr.predict(X_test))
print('y_test = ', y_test)

y_hat =  [1 2 0 1 2 0 2 1 0 1 1 1 0 0 1 1 1 1 1 0 1 1 0 1 0 2 0 2 1 2 2 0 1 1 1 0 1
 1 1 0 1 1 1 1 1]
y_test =  [1 2 0 1 2 0 2 1 0 1 1 1 0 0 1 1 1 1 1 0 1 1 0 1 0 2 0 2 1 2 2 0 1 1 1 0 1
 1 1 0 1 1 1 1 1]


TO DO: Display the result of simple_lr.probability(X_test).
Then, check whether the sum of each row makes one.

In [303]:
prob = simple_lr.probability(X_test)
print('prob = ' , prob)
print('The sum of rows = ', np.sum(prob, axis=1))

prob =  [[4.04048410e-04 9.99554828e-01 4.11231731e-05]
 [3.03037629e-03 4.48925880e-02 9.52077036e-01]
 [9.99580859e-01 7.77189456e-07 4.18364168e-04]
 [5.73385384e-02 9.42099868e-01 5.61593100e-04]
 [2.00053265e-04 3.19792675e-02 9.67820679e-01]
 [9.41175546e-01 2.90025437e-02 2.98219107e-02]
 [2.67945807e-04 3.08636362e-05 9.99701191e-01]
 [1.29855668e-01 8.27519415e-01 4.26249176e-02]
 [9.95108229e-01 3.09362953e-03 1.79814122e-03]
 [2.06458086e-03 9.97346712e-01 5.88707217e-04]
 [1.18956482e-03 9.98462991e-01 3.47444182e-04]
 [8.96308658e-04 9.98369797e-01 7.33894785e-04]
 [9.99373755e-01 1.98090022e-05 6.06436351e-04]
 [9.98389502e-01 1.18989735e-04 1.49150841e-03]
 [1.57040178e-04 9.99814648e-01 2.83122372e-05]
 [1.46535742e-01 8.52026921e-01 1.43733713e-03]
 [2.38843268e-04 9.99617318e-01 1.43838414e-04]
 [9.72374680e-04 9.98940596e-01 8.70296873e-05]
 [4.48774354e-04 9.99531714e-01 1.95113567e-05]
 [7.44643540e-01 2.30744008e-01 2.46124520e-02]
 [1.84123010e-03 9.97877868e-01 

TO DO: Print the accuracy on the training and test data.

In [304]:
simple_lr = SimpleLinearClassifier(W_lr, b_lr)
print('tran score = ', simple_lr.score(X_train, y_train))
print('test score = ', simple_lr.score(X_test, y_test))

tran score =  0.9624060150375939
test score =  1.0


TO DO: Create a SimpleLinearClassfier instance simple_svc using W_svc and b_svc. Then, print the accuracy on the training and test data.<br>
(The accuracies should be the same as those of the LinearSVC instance.)

In [305]:
simple_svc = SimpleLinearClassifier(W_svc, b_svc)
print('train score = ', simple_svc.score(X_train, y_train))
print('test score = ', simple_svc.score(X_test, y_test))

train score =  0.8571428571428571
test score =  0.9555555555555556


TO DO: Display the results of simple_svc.predict(X_test) along with y_test.

In [306]:
print('y_hat = ' , simple_svc.predict(X_test))
print('y_test = ', y_test)

y_hat =  [1 2 0 1 2 2 2 1 0 1 1 1 0 0 1 1 1 1 1 1 1 1 0 1 0 2 0 2 1 2 2 0 1 1 1 0 1
 1 1 0 1 1 1 1 1]
y_test =  [1 2 0 1 2 0 2 1 0 1 1 1 0 0 1 1 1 1 1 0 1 1 0 1 0 2 0 2 1 2 2 0 1 1 1 0 1
 1 1 0 1 1 1 1 1]


TO DO: Display the result of simple_svc.probability(X_test).
Then, check whether the sum of each row makes one.

In [307]:
prob = simple_svc.probability(X_test)
print('prob = ' , prob)
print('The sum of rows = ', np.sum(prob, axis=1))

prob =  [[0.04085706 0.79214136 0.16700158]
 [0.05554563 0.30474118 0.63971319]
 [0.71052024 0.01407781 0.27540195]
 [0.17292401 0.53178421 0.29529177]
 [0.02433396 0.41362108 0.56204495]
 [0.31451792 0.3182805  0.36720158]
 [0.04059508 0.09975861 0.85964631]
 [0.24143685 0.40421567 0.35434748]
 [0.47924789 0.13710108 0.38365103]
 [0.05311144 0.77066018 0.17622838]
 [0.06132362 0.72526319 0.21341319]
 [0.04905448 0.66798226 0.28296326]
 [0.65331307 0.03838058 0.30830635]
 [0.64941971 0.05764604 0.29293424]
 [0.03812107 0.83293746 0.12894146]
 [0.14987091 0.58563672 0.26449237]
 [0.01891428 0.84159343 0.13949229]
 [0.07403298 0.76329483 0.16267219]
 [0.04084755 0.83773444 0.12141801]
 [0.26903899 0.38302767 0.34793334]
 [0.05977401 0.69886153 0.24136446]
 [0.09261519 0.62488    0.28250481]
 [0.76344077 0.01540574 0.22115349]
 [0.10952635 0.51309072 0.37738293]
 [0.48347429 0.08012143 0.43640429]
 [0.13153804 0.20603281 0.66242915]
 [0.54458162 0.12958955 0.32582882]
 [0.02844163 0.09570

TO DO: Print the accuracy on the training and test data.

In [308]:
print('train score = ', simple_svc.score(X_train, y_train))
print('test score = ', simple_svc.score(X_test, y_test))

train score =  0.8571428571428571
test score =  0.9555555555555556
